---

- name: ensure homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: install homebrew
  when: not homebrew_check.stat.exists
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: re-eval source
  shell: source ~/.zshrc

- name: ensure homebrew is updated 
  homebrew:
    state: latest
    update_homebrew: yes
    upgrade_all: yes

- name: tap casks
  homebrew_tap:
    tap: "{{ homebrew.casks }}"
    state: present

- name: install cask applications
  homebrew_cask:
    name: "{{ homebrew.applications }}"
    state: present
    accept_external_apps: yes

- name: install homebrew packages
  homebrew:
    name: "{{ homebrew.packages }}"
    state: present

