---

- name: set files path
  set_fact:
    files_path: "{{ role_path }}/files"
  tags:
    - always

- name: configure terminal 
  import_tasks: terminal.yml
  tags:
    - terminal

- name: install homebrew and install
  import_tasks: homebrew.yml
  tags:
    - brew

- name: setup node dev environment
  import_tasks: node.yml
  tags:
    - node
