---

- name: link dotfiles
  file:
    src: "{{ files_path }}/{{ item }}"
    dest: "${HOME}/{{ item }}"
    state: link
    force: yes
    follow: false
  loop:
    - .zshrc

- name: set global git name
  command: git config --global user.name "Luke Browne"

- name: set global git email
  command: git config --global user.email "git@lukeb.me"

